name:                flocking-demo
version:             0.1.0.0
github:              "badly-drawn-wizards/flocking-demo"
license:             BSD3
author:              "Reuben Steenekamp"
maintainer:          "reuben.steenekamp@gmail.com"
copyright:           "2020 Reuben Steenekamp"

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         A demo of flocking behaviour


executables:
  flock:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - containers
    - KdTree
    - lens
    - generic-lens
    - linear
    - gloss
    - mtl
    - MonadRandom
